WIP: start app in main
nix-provided quickfix does not seem to have ssl support. This results in the following error:
```
harjus/harjus-port/src/Main.cpp:67:(.text+0x330): undefined reference to `FIX::ThreadedSSLSocketInitiator::ThreadedSSLSocketInitiator(FIX::Application&, FIX::MessageStoreFactory&, FIX::SessionSettings const&, FIX::LogFactory&)'
```

 May need to package quickfix myself